[project]
name = "hello-durable-function"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-functions>=1.24.0",
    "azure-functions-durable>=1.4.0",
]
